# Source File: mssub_mcp_unit_test.toml
# Location:    musebms/database/buildplans.mssub_mcp_unit_test.toml
# Project:     Muse Systems Business Management System
#
# Copyright Â© Lima Buttgereit Holdings LLC d/b/a Muse Systems
# This file may include content copyrighted and licensed from third parties.
#
# See the LICENSE file in the project root for license terms and conditions.
# See the NOTICE file in the project root for copyright ownership information.
#
# muse.information@musesystems.com :: https://muse.systems

##
##  NOTE:  This build plan exists only to facilitate automated testing,
##         continuous integration, and other similar development & testing
##         activities.  It is not used to build released software.
##

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 820
sponsor_modification = 0
load_files = [ {type = "plan", file = "buildplans.mssub_mcp.toml"} ]

[[build_plan]]
release              = 1
version              = 1
update               = 0
sponsor              = 821
sponsor_modification = 0
load_files = [
    "subsystems/mssub_mcp/testing_support/test_privileges.eex.sql",
    "components/system/mscmp_syst_settings/testing_support/test_data.eex.sql",
    "components/system/mscmp_syst_instance/testing_support/test_data_unit_test.eex.sql",
    "components/system/mscmp_syst_authn/testing_support/test_data_unit_test.eex.sql",
    "components/system/mscmp_syst_session/testing_support/test_data_unit_test.eex.sql",
 ]
